##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gettext
    - gcc
    - git
    - libbaul-extension-dev
    - libglib2.0-dev
    - libjson-glib-dev
    - libmagic-dev
    - librest-0.7-0 #required for ctk
    - libtool
    - make
    - wget
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 ctk-update-icon-cache'

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/cafe-desktop/grapa/raw/master/data/icons/16x16/apps/grapa.png; fi
