##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gettext
    - gcc
    - git
    - libcaja-extension-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libjson-glib-dev
    - libmagic-dev
    - libtool
    - make
    - yelp-tools

before_scripts:
  - ./html-cppcheck
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master

build_scripts:
  - mkdir html-report
  - cppcheck $ARGS_CPPCHECK . 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}

  - ./make-scanbuild '--enable-compile-warnings=maximum'

  - apt list --installed cafe-common libctk-3-dev 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo Errors detected in the build `cat ./html-report/output_${TRAVIS_COMMIT} | grep ' error:' | grep -v "\[" | wc -l` 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}
  - echo Warnings detected in the logs `cat ./html-report/output_${TRAVIS_COMMIT} | grep -i warning | wc -l` 2>&1 | tee -a ./html-report/output_${TRAVIS_COMMIT}


after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
