Document: grapa
Title: Debian grapa Manual
Author: <insert document author here>
Abstract: This manual describes what grapa is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/grapa/grapa.sgml.gz

Format: postscript
Files: /usr/share/doc/grapa/grapa.ps.gz

Format: text
Files: /usr/share/doc/grapa/grapa.text.gz

Format: HTML
Index: /usr/share/doc/grapa/html/index.html
Files: /usr/share/doc/grapa/html/*.html
